language: java

env:
  - OUTPUT_DIR=target ARTIFACT_NAME=java-tooling-template ARTIFACT_EXTENSION=.jar

install:
- mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -V

sudo: false

script:
- mvn test -B

before_deploy:
- tar -zcf $TRAVIS_BUILD_DIR/$OUTPUT_DIR/$TRAVIS_TAG.tar.gz -C $TRAVIS_BUILD_DIR/$OUTPUT_DIR $(find $TRAVIS_BUILD_DIR/$OUTPUT_DIR/ -maxdepth 1 -name $ARTIFACT_NAME-*$ARTIFACT_EXTENSION -printf "%f\n")

cache:
  directories:
  - $HOME/.m2

deploy:
- provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/$OUTPUT_DIR/$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(([0-9]).)+([0-9]+$)

- provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "$TRAVIS_BUILD_DIR/$OUTPUT_DIR/$TRAVIS_TAG.tar.gz"
  skip_cleanup: true
  name: $TRAVIS_TAG
  prerelease: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^$*-*(beta|alpha|pre).*$